name: TrippyTime
version: 1.0
api: [1.0.0]
author: [mightysun99 & MegaSamNinja]
description: N/A
main: mightysun99\TrippyTime\Main
load: POSTWORLD
website: N/A
commands:
    trippytime:
      description: Enables Trippy Time
      usage: "Usage: /enabletrippytime"
permissions:
    trippytime:
        default: false
        description: Permission to do command
        children:
            trippytime.command:
              default: false
              description: Switches the server into random time intervals 
